### ISSUE TITLE
Buttons are confusing -- need to fix before publishing

### ISSUE THREAD

**Issue by jaceybee** [clickonetwo/whisper#11]
To eliminate confusion about whispering/listening over Bluetooth vs over the net, I propose we get rid of the Whisper/Listen by URL buttons altogether. Instead, there will be two buttons: Whisper and Listen.

When you click on Whisper, you will see a button to send a link for remote listeners. That button will allow you to share the link in all the various ways Apple allows (text, email, copy link, etc.). It doesn't make much sense to have an AirDrop function, since if they're on a device with AirDrop and close enough for it to work, they'll be connected by Bluetooth.

When you click on the Listen app, you'll connect over Bluetooth. If you're listening remotely, you just have to wait for the link to come from the whisperer, and when you click that it'll open the conversation in your browser (and Apple devices will have the option to go to app from there).

**Comment by brotskydotcom2** [comment]
I agree that there should just be two buttons.  But let me clarify the behavior that happens when a link is received/clicked-on:

**IF** you're on an iOS or macOS device **AND** you have the app:

- If the app is not running, it will be launched and immediately start to listen to the whisperer who sent the link.
- If the app is running in the "choice" screen (with the name and the buttons), it will immediately start to listen to the whisperer who sent the link.
- If the app is running and is already whispering or listening, it will display an alert that says "Already whispering/listening to someone else.  Stop whispering/listening and click the link again." (or your better words to that effect).

**OTHERWISE**:

- A new browser window (or tab) will appear and start listening to the whisperer who sent the link. (If this is the very first time you have used your browser to listen, you will be required to enter your name before you can listen.)

**Comment by brotskydotcom2** [comment]
I've done some research and Apple will not automatically tell you about the app in your browser.  So I've revised my last comment accordingly.  That should make the instructions a lot simpler.

**Comment by jaceybee** [comment]
Awesome!
