### ISSUE TITLE
Preference changes

### ISSUE THREAD

**Issue by brotskydotcom2** [clickonetwo/whisper#9]
Please make the following changes:

1. Remove preference for "Your Name"
2. Add preference for "Remember name from last session" (toggle on/off), default on
3. Remove preference for "initial mode"
4. Change name of "listener layout matches whisperer" to be a single select named "Newest whisper appears at" with choices "top"/"bottom" (default "top")
5. Change name to "Require Bluetooth listeners to pair"

**Comment by brotskydotcom2** [comment]
So the "Newest whisper appears at" preference name is confusing because it only applies to the listener, not also to the whisperer.  I am changing it to be "Listener sees newest whisper appear at" with choices "Top"/"Bottom".  The alternative would be to talk about the window the listener sees, so "Listener sees newest whisper appear in" with choices "Top window"/"Bottom window"

@jaceybee I need you to weigh in on this - which do you prefer?

**Comment by clickonetwo** [comment]
So the "Newest whisper appears at" preference name is confusing because it only applies to the listener, not also to the whisperer.  I am changing it to be "Listener sees newest whisper appear at" with choices "Top"/"Bottom".  The alternative would be to talk about the window the listener sees, so "Listener sees newest whisper appear in" with choices "Top window"/"Bottom window"

@jaceybee I need you to weigh in on this - which do you prefer?

**Comment by brotskydotcom2** [comment]
Per conversation with @jaceybee, final language is:

“Listener sees newest whisper in [Top window/Bottom window]”
